/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZenkaiEscrow,
  IZenkaiEscrowInterface,
} from "../../../contracts/ZenkaiVerifier.sol/IZenkaiEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
    ],
    name: "openDisputeWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "matchId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    name: "settleMatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZenkaiEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IZenkaiEscrowInterface {
    return new Interface(_abi) as IZenkaiEscrowInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZenkaiEscrow {
    return new Contract(address, _abi, runner) as unknown as IZenkaiEscrow;
  }
}
