/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZenkaiEscrow } from "./IZenkaiEscrow";
export type { ZenkaiVerifier } from "./ZenkaiVerifier";
