/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zenkaiVerifierSol from "./ZenkaiVerifier.sol";
export type { zenkaiVerifierSol };
import type * as mock from "./mock";
export type { mock };
export type { ZenkaiEscrow } from "./ZenkaiEscrow";
export type { ZenkaiTreasury } from "./ZenkaiTreasury";
