/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZenkaiEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMELOCK_DURATION"
      | "anchorMoveHashes"
      | "cUSD"
      | "createMatch"
      | "createMatchWithPermit"
      | "executeNewVerifier"
      | "gameServer"
      | "joinMatch"
      | "joinMatchWithPermit"
      | "matches"
      | "openDisputeWindow"
      | "owner"
      | "pendingVerifier"
      | "proposeNewVerifier"
      | "recordForfeit"
      | "renounceOwnership"
      | "resolveDispute"
      | "settleMatch"
      | "settleMatchDraw"
      | "stakeAmounts"
      | "transferOwnership"
      | "treasury"
      | "verifier"
      | "verifierTimelockExpiry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "ForfeitRecorded"
      | "MatchCreated"
      | "MatchDrawn"
      | "MatchLocked"
      | "MatchSettled"
      | "MoveHashesAnchored"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMELOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anchorMoveHashes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "cUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatchWithPermit",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeNewVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gameServer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatchWithPermit",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "matches", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "openDisputeWindow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeNewVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordForfeit",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleMatch",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleMatchDraw",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAmounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierTimelockExpiry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TIMELOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorMoveHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatchWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeNewVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gameServer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinMatchWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDisputeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeNewVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordForfeit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleMatchDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierTimelockExpiry",
    data: BytesLike
  ): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [matchId: BytesLike, expiryTime: BigNumberish];
  export type OutputTuple = [matchId: string, expiryTime: bigint];
  export interface OutputObject {
    matchId: string;
    expiryTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForfeitRecordedEvent {
  export type InputTuple = [matchId: BytesLike, forfeitingPlayer: AddressLike];
  export type OutputTuple = [matchId: string, forfeitingPlayer: string];
  export interface OutputObject {
    matchId: string;
    forfeitingPlayer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    p1: AddressLike,
    gameType: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    matchId: string,
    p1: string,
    gameType: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    matchId: string;
    p1: string;
    gameType: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchDrawnEvent {
  export type InputTuple = [matchId: BytesLike, payoutEach: BigNumberish];
  export type OutputTuple = [matchId: string, payoutEach: bigint];
  export interface OutputObject {
    matchId: string;
    payoutEach: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchLockedEvent {
  export type InputTuple = [
    matchId: BytesLike,
    p2: AddressLike,
    seed: BytesLike
  ];
  export type OutputTuple = [matchId: string, p2: string, seed: string];
  export interface OutputObject {
    matchId: string;
    p2: string;
    seed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSettledEvent {
  export type InputTuple = [
    matchId: BytesLike,
    winner: AddressLike,
    payout: BigNumberish
  ];
  export type OutputTuple = [matchId: string, winner: string, payout: bigint];
  export interface OutputObject {
    matchId: string;
    winner: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveHashesAnchoredEvent {
  export type InputTuple = [matchId: BytesLike, rootHash: BytesLike];
  export type OutputTuple = [matchId: string, rootHash: string];
  export interface OutputObject {
    matchId: string;
    rootHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZenkaiEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ZenkaiEscrow;
  waitForDeployment(): Promise<this>;

  interface: ZenkaiEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMELOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  anchorMoveHashes: TypedContractMethod<
    [matchId: BytesLike, rootHash: BytesLike],
    [void],
    "nonpayable"
  >;

  cUSD: TypedContractMethod<[], [string], "view">;

  createMatch: TypedContractMethod<
    [gameType: BigNumberish, tier: BigNumberish],
    [string],
    "nonpayable"
  >;

  createMatchWithPermit: TypedContractMethod<
    [
      gameType: BigNumberish,
      tier: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  executeNewVerifier: TypedContractMethod<[], [void], "nonpayable">;

  gameServer: TypedContractMethod<[], [string], "view">;

  joinMatch: TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;

  joinMatchWithPermit: TypedContractMethod<
    [
      matchId: BytesLike,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  matches: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        p1: string;
        p2: string;
        stakeAmount: bigint;
        gameType: bigint;
        seed: string;
        state: bigint;
        lastActionTime: bigint;
        disputeWindowExpiry: bigint;
        winner: string;
      }
    ],
    "view"
  >;

  openDisputeWindow: TypedContractMethod<
    [matchId: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingVerifier: TypedContractMethod<[], [string], "view">;

  proposeNewVerifier: TypedContractMethod<
    [_newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  recordForfeit: TypedContractMethod<
    [matchId: BytesLike, forfeitingPlayer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [matchId: BytesLike],
    [void],
    "nonpayable"
  >;

  settleMatch: TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  settleMatchDraw: TypedContractMethod<
    [matchId: BytesLike],
    [void],
    "nonpayable"
  >;

  stakeAmounts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifierTimelockExpiry: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMELOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "anchorMoveHashes"
  ): TypedContractMethod<
    [matchId: BytesLike, rootHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [gameType: BigNumberish, tier: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMatchWithPermit"
  ): TypedContractMethod<
    [
      gameType: BigNumberish,
      tier: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeNewVerifier"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "gameServer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "joinMatch"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "joinMatchWithPermit"
  ): TypedContractMethod<
    [
      matchId: BytesLike,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        p1: string;
        p2: string;
        stakeAmount: bigint;
        gameType: bigint;
        seed: string;
        state: bigint;
        lastActionTime: bigint;
        disputeWindowExpiry: bigint;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openDisputeWindow"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeNewVerifier"
  ): TypedContractMethod<[_newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordForfeit"
  ): TypedContractMethod<
    [matchId: BytesLike, forfeitingPlayer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleMatch"
  ): TypedContractMethod<
    [matchId: BytesLike, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleMatchDraw"
  ): TypedContractMethod<[matchId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeAmounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierTimelockExpiry"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "ForfeitRecorded"
  ): TypedContractEvent<
    ForfeitRecordedEvent.InputTuple,
    ForfeitRecordedEvent.OutputTuple,
    ForfeitRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchDrawn"
  ): TypedContractEvent<
    MatchDrawnEvent.InputTuple,
    MatchDrawnEvent.OutputTuple,
    MatchDrawnEvent.OutputObject
  >;
  getEvent(
    key: "MatchLocked"
  ): TypedContractEvent<
    MatchLockedEvent.InputTuple,
    MatchLockedEvent.OutputTuple,
    MatchLockedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;
  getEvent(
    key: "MoveHashesAnchored"
  ): TypedContractEvent<
    MoveHashesAnchoredEvent.InputTuple,
    MoveHashesAnchoredEvent.OutputTuple,
    MoveHashesAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(bytes32,uint256)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "ForfeitRecorded(bytes32,address)": TypedContractEvent<
      ForfeitRecordedEvent.InputTuple,
      ForfeitRecordedEvent.OutputTuple,
      ForfeitRecordedEvent.OutputObject
    >;
    ForfeitRecorded: TypedContractEvent<
      ForfeitRecordedEvent.InputTuple,
      ForfeitRecordedEvent.OutputTuple,
      ForfeitRecordedEvent.OutputObject
    >;

    "MatchCreated(bytes32,address,uint8,uint8)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchDrawn(bytes32,uint256)": TypedContractEvent<
      MatchDrawnEvent.InputTuple,
      MatchDrawnEvent.OutputTuple,
      MatchDrawnEvent.OutputObject
    >;
    MatchDrawn: TypedContractEvent<
      MatchDrawnEvent.InputTuple,
      MatchDrawnEvent.OutputTuple,
      MatchDrawnEvent.OutputObject
    >;

    "MatchLocked(bytes32,address,bytes32)": TypedContractEvent<
      MatchLockedEvent.InputTuple,
      MatchLockedEvent.OutputTuple,
      MatchLockedEvent.OutputObject
    >;
    MatchLocked: TypedContractEvent<
      MatchLockedEvent.InputTuple,
      MatchLockedEvent.OutputTuple,
      MatchLockedEvent.OutputObject
    >;

    "MatchSettled(bytes32,address,uint256)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;

    "MoveHashesAnchored(bytes32,bytes32)": TypedContractEvent<
      MoveHashesAnchoredEvent.InputTuple,
      MoveHashesAnchoredEvent.OutputTuple,
      MoveHashesAnchoredEvent.OutputObject
    >;
    MoveHashesAnchored: TypedContractEvent<
      MoveHashesAnchoredEvent.InputTuple,
      MoveHashesAnchoredEvent.OutputTuple,
      MoveHashesAnchoredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
